version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    commit-message:
      prefix: ci
      include: scope
    reviewers:
      - g10z3r
      - jevgenis33
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    commit-message:
      prefix: build(rust)
      prefix-development: chore(rust)
    reviewers:
      - brutusyhy
    labels:
      - dependencies
      - rust
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    commit-message:
      prefix: build(typescript)
      prefix-development: chore(typescript)
    reviewers:
      - Enthceph
      - jevgenis33
    labels:
      - dependencies
      - typescript
    open-pull-requests-limit: 10
