[workspace]
workspace.resolver = "2"
members = [
    "crates/moss-desktop",
    "crates/moss-cache",
    "crates/moss-text",
    "crates/moss-jsonlogic",
    "crates/moss-jsonlogic-macro",
    "crates/moss-env",
    "crates/moss-tauri",
    "view/desktop/bin",
]

[workspace.dependencies]
moss_desktop = { path = "crates/moss-desktop" }
moss_cache = { path = "crates/moss-cache" }
moss_text = { path = "crates/moss-text" }
moss_jsonlogic = { path = "crates/moss-jsonlogic" }
moss_jsonlogic_macro = { path = "crates/moss-jsonlogic-macro" }
moss_env = { path = "crates/moss-env" }
moss_tauri = { path = "crates/moss-tauri" }


bstr = "1.11.3"
dashmap = "6.1.0"
moka = { version = "0.12.10", features = ["sync"] }
thiserror = "2.0.11"
anyhow = "1.0.95"
hcl-rs = "0.18.4"
serde = "1.0.217"
serde_json = "1.0.138"
hashbrown = "0.15.2"
arcstr = "1.2.0"
petgraph = "0.7.1"
strum = "0.27.0"
phf = "0.11.3"
rand = { version = "0.9.0" }
parking_lot = "0.12.3"
ctor = "0.3.0"
derive_more = "2.0.1"
fnv = "1.0.7"
once_cell = "1.20.3"

tokio = "1.43.0"
tauri = { version = "2.0.6", features = ["devtools"] }

tracing = "0.1"
tracing-subscriber = "0.3.18"
tracing-appender = "0.2.3"
log = "0.4.25"
dirs = "6.0.0"

ts-rs = "10.1.0"