[workspace]
workspace.resolver = "2"
members = [
    "crates/moss-cache",
    "crates/moss-desktop",
    "crates/moss-env",
    "crates/moss-jsonlogic",
    "crates/moss-jsonlogic-macro",
    "crates/moss-tauri",
    "crates/moss-text",
    "tools/xtask",
    "view/desktop/bin",
]

[workspace.dependencies]
moss_cache = { path = "crates/moss-cache" }
moss_desktop = { path = "crates/moss-desktop" }
moss_env = { path = "crates/moss-env" }
moss_jsonlogic = { path = "crates/moss-jsonlogic" }
moss_jsonlogic_macro = { path = "crates/moss-jsonlogic-macro" }
moss_tauri = { path = "crates/moss-tauri" }
moss_text = { path = "crates/moss-text" }

tauri = { version = "2.2.5", default-features = false }

anyhow = "1.0.95"
arcstr = "1.2.0"
bstr = "1.11.3"
clap = { version = "4.5.28", features = ["derive"] }
dashmap = "6.1.0"
derive_more = "2.0.1"
dirs = "6.0.0"
fnv = "1.0.7"
futures = "0.3.31"
log = "0.4.25"
moka = { version = "0.12.10", features = ["sync"] }
once_cell = "1.20.3"
parking_lot = "0.12.3"
rand = { version = "0.9.0" }
serde = "1.0.217"
serde_json = "1.0.138"
smol = "2.0.2"
strum = "0.27.0"
thiserror = "2.0.11"
tokio = "1.43.0"
tracing = "0.1"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.18"
ts-rs = "10.1.0"