[package]
name = "moss-git"
version = "0.1.0"
edition = "2021"

[dependencies]
git2.workspace = true
oauth2 = { workspace = true, features = ["reqwest-blocking"] }
reqwest = { workspace = true, features = ["blocking"] } # Using blocking for easy testing here

# Making SSH work on Windows
[target.'cfg(windows)'.dependencies]
openssl = { version = "0.10.70", features = ["vendored"] }
ssh2 = { workspace = true, features = ["openssl-on-win32", "vendored-openssl"] }
